### ISSUE TITLE
Provide UI for propose-downstream

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1082]
By now, there is no way how we can get information about the progress of the propose-downstream job.

* [x] packit/packit-service#1292
* [x] packit/dashboard#155
* [x] packit/packit-service#1293
* [ ] ~~packit/packit-service#1080~~ We have logs view but not the real-time ones. Let's move the real-time logs away.

*This is a part of our UX effort to provide more information to users about the process of ongoing packit-service jobs.*

**Comment by lachmanfrantisek** [comment]
I am marking this as done!
