### ISSUE TITLE
Improve user-experience when things go bad

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1158]
This is a meta issue to cover other concrete tasks to improve UX when builds fail or there are some infra problems.

* [ ] ~~https://github.com/packit/packit-service/issues/927~~ changed to an epic itself
* [x] #540
* [x] #701 
* [x] #765 
* [x] https://github.com/packit/packit-service/issues/1145
* [x] https://github.com/packit/packit-service/issues/1005
* [x] #1035

**Comment by lachmanfrantisek** [comment]
The first task became an epic itself. Closing since the rest of the tasks is done. Nice!
