### ISSUE TITLE
Support repository-cache

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1165]
- [x] support in packit (https://github.com/packit/packit/pull/1214 https://github.com/packit/packit/pull/1253)
- [x] use in service code (https://github.com/packit/packit-service/pull/1098)
- [x] use in workers (https://github.com/packit/deployment/pull/210)
- [x] use in sandcastle:
  - [x] be able to configure volumes for sandcastle (https://github.com/packit/packit/pull/1274 a related one: https://github.com/packit/sandcastle/pull/135)
  - [x] deploy the pods for sandcastle (https://github.com/packit/deployment/pull/210)
- [x] https://github.com/packit/packit-service/issues/1170
- [ ]  https://github.com/packit/deployment/issues/228

Nice to have:
- [x] https://github.com/packit/packit-service/issues/1184
- [x] https://github.com/packit/packit-service/issues/1181
- [x] https://github.com/packit/sandcastle/issues/141
- [x] https://github.com/packit/deployment/issues/234
- [ ] Automate the cache update

**Comment by TomasTomecek** [comment]
@lachmanfrantisek notes:
* check in our current cluster if we can have read-many volumes
* or even read-write many
* once we get rid of sandcastle, this will be much simpler
