### ISSUE TITLE
Pull from upstream

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1576]
Users can configure the Packit job to trigger `propose-downstream` workflow in downstream. The presence of Packit is not required upstream; the information about the new version can be obtained from NewHotnes messages.

The workflow should look like this:

Configuration:
* User configures a job in the Packit config in the dist-git repository.
* User adds the project to https://release-monitoring.org/

Release workflow:
* Packit is notified about the new releases via UpstreamReleaseMonitoring/Anytia/NewHotness.
* Packit checks if a user has the job configured. (Probably in the `main` branch of the dist-git repo.)
* Packit triggers the very same workflow as we do for `propose-downstream` job:
  * Source archive is downloaded and sent to the lookaside cache.
  * For each configured dist-git branch, the PR is created with spec/sources file updated.

Subtasks:
* [x] #1577
* [x] #1578
* [x] packit/packit.dev#495
* [x] packit/packit.dev#494
* [x] packit/packit.dev#496

**Comment by csomh** [comment]
> * Packit checks if a user has the job configured. (Probably in the `main` branch of the dist-git repo.)

Would it make sense to have this configured on a per-branch basis, that is, when notified about a new release, Packit checks each active branch of the package and proposes an update for the ones which have the configuration? This way it would be easier to tell if a branch is going to be updated by Packit.

**Comment by Conan-Kudo** [comment]
This would be very useful and interesting for broader adoption of Packit automation.
