### ISSUE TITLE
Build SRPMs used for Copr builds in Copr

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1682]
All the SRPMs used for Copr builds are done in Copr.

Reason:
* Packit team does not need to develop and maintain a sandboxing solution (=[sandcastle](https://github.com/packit/sandcastle)).
* Users are able to set the dependencies for actions (=user-defined commands) themselves.

Issues:
* [x] https://github.com/packit/packit/issues/1409
* [x] https://github.com/packit/packit/issues/1410
* [x] https://github.com/packit/packit-service/issues/1270
* [x] https://github.com/packit/packit-service/issues/1562
* [x] https://github.com/packit/packit/issues/1637
* [x] https://github.com/packit/packit-service/issues/1583
* [x] https://github.com/packit/packit-service/issues/1582
* [x] #1801 
* [x] #1691

**Comment by lbarcziova** [comment]
Since all the subtasks here are now implemented, I think we can close this, right?

**Comment by mfocko** [comment]
Yes! :bouquet: please do the honors :smile:
