### ISSUE TITLE
Automate moving of the stable branches

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1698]
We'd like to automate moving the stable branches and creating a blog post so that the scripts don't need to be run locally. 

Definition of done:
* [ ] moving of the stable branches and creation of the weekly packit.dev blog posts are run in a Github action
  * [ ] the work that is currently done by running a script locally will be moved to a GitHub action that can be triggered manually in Github UI (=> the script can run non-interactively)
  * [ ] the PR with the blog post will be opened automatically by running the action and the content can be modified by a person
* [ ] instructions for the Service Guru role are updated
