### ISSUE TITLE
Warn users via commit checks about switching SRPM building

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1801]
- [ ] document that we are going to switch to SRPMs (for Copr build job) in Copr in January - packit/packit.dev/pull/571
- [ ] if we are processing a Copr build job and `srpm_build_deps` is not defined in the config, create an error state [similarly as here](https://github.com/packit/packit-service/blob/98531fb62e6d4d8c4e233d07a3c6fb7fcc1de17c/packit_service/worker/jobs.py#L422): mention the plan to switch, link relevant docs, ask users to define the field - #1804 
- [ ] when deployed, try to observe whether the waning actually helped and whether users added this field after receiving the warning

**Comment by TomasTomecek** [comment]
The last point is not a must-have but I'd appreciate a few examples where people actually do the change based on the warning :)

**Comment by jpopelka** [comment]
Sure, that's why it's still in in-review.

**Comment by jpopelka** [comment]
Here are (most of) the projects which received the warning after this PR was merged and most of them have switched to `srpm_build_deps` since then:

- [x] ComplianceAsCode/content#10003
- [ ] facebook/CacheLib
- [x] facebook/time#239
- [x] oamg/leapp-repository#848
- [x] OpenSCAP/openscap-report#122
- [x] osandov/drgn#230
- [ ] rear/rear
- [ ] StykMartin/openbeaker
- [x] teemtee/tmt#1760

**Comment by TomasTomecek** [comment]
Perfect, thank you very much for collecting these!
