### ISSUE TITLE
GitLab UX

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1821]
Follow-up from the meetings with polkit/bolt maintainers (freedesktop.org GitLab instance) and IRC discussions (gnome.org GitLab instance).

- [ ] testing and verification of GitLab
  - [ ] extending/refactoring unit tests - should be contained in a separate issue, since they cover more than just GitLab; also the GitLab coverage is minimal, which has been already discovered in dysfunctional Packit on GitLab after a refactor
  - [ ] functional tests (extending validation scripts) - recently we have lost a production user on gnome.org instance and the exception caught by Sentry did not suggest this option in any way, we should be able to both monitor the accessibility and uptime on other instances and verify that basic workflows are functioning
    - [ ] public gitlab.com instance
    - [ ] freedesktop.org instance
    - [ ] gnome.org instance
- [ ] status reporting and permissions
   currently we need to have permissions for setting pipeline statuses and this workflow can be a „little“ intimidating for the first-time contributors.
   GitLab now supports history for the comments on MRs, so one of my ideas is to have »one« Packit comment containing commit hash, timestamps and all of the statuses updated over time (also with a history). Such as
   ```
   <!-- packit-stg CI; »do not edit« -->
   commit hash: aaaaaaa
   updated: 2023-01-02 12:34:56

   | Job                                               | Status  |
   | ------------------------------------------------- | ------- |
   | [rpm-build:fedora-rawhide-x86_64](dashboard link) | success |
   ```

---

If there is anything else I have forgotten, please comment (or add a TODO item directly, if you have permissions to do so).

**Comment by lachmanfrantisek** [comment]
After a team discussion, we didn't pick this as a top Packit team priority for the next quarter and preferred epics with bigger user benefits. (Sadly, we have limited resources.) If anyone wants to help us with this, we will be really glad. We are open to any collaboration and have successfully implemented/started multiple affords thanks to people outside of the Packit team.
