### ISSUE TITLE
Database improvements

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1848]
Follow-ups of the [research](https://github.com/packit/research/pull/128):

* [x] https://github.com/packit/packit-service/issues/1326
* [x] https://github.com/packit/packit-service/issues/1327
* [x] https://github.com/packit/packit-service/issues/1864
  * [x] #1985 
  * [x] #1986 
  * [ ] updated #1773 
* [x] https://github.com/packit/packit-service/issues/1328
* [ ] https://github.com/packit/packit-service/issues/1329

#### Related issues / follow-ups

* [x] https://github.com/packit/packit-service/issues/1908
* [ ] https://github.com/packit/packit-service/issues/1889
* [ ] https://github.com/packit/packit-service/issues/1890
* [ ] https://github.com/packit/packit-service/issues/1882
* [x] https://github.com/packit/packit-service/issues/1679
* [ ] https://github.com/packit/packit-service/issues/1784
* [ ] https://github.com/packit/packit-service/issues/1779
* [x] ~https://github.com/packit/packit-service/issues/1749~

**Comment by majamassarini** [comment]
Just one more note:

When working at packit/packit-service#1908 I realized we are making really a lot of small speedy queries (almost always the same) when reacting to an event.

@TomasTomecek suggested to try to improve the `ORM` working together during an hackfest.

**Comment by lachmanfrantisek** [comment]
I am going to close this epic since we've done the key part. The next steps will be done by user-targeted epics/tasks.
