### ISSUE TITLE
Market downstream automation (Koji builds, Bodhi updates) more

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1934]
@xsuchy proposed to market the dist-git-only jobs more since many people might still not be aware of this functionality. In the past, we already wrote a [blog post](https://packit.dev/posts/downstream-automation/) and there is also a [Fedora releases guide](https://packit.dev/docs/fedora-releases-guide/)  in packit.dev which could be reused.

Proposed TODOs:
- [ ] make sure the docs are up to date, easy to navigate
- [ ] write to Fedora magazine
- [ ] workshop (Fedora Classroom)
- [ ] Youtube video 
- [ ] feel free to add something

Discuss and agree on the things to do with the team.

**Comment by lachmanfrantisek** [comment]
We have this covered elsewhere...
