### ISSUE TITLE
Job dependencies

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2105]
The outcome of this card will be that users will be able to explicitly configure dependencies between jobs => reference which job needs to be run before some other job.

TODO:
- [ ] packit/packit-service#2033
- [ ] packit/packit-service#1773
- [ ]  packit/packit-service#1720

**Comment by praiskup** [comment]
Just for reference, before it gets lost -> #2169 contains a dummy pseudocode for chaining Copr builds specifically (not sure if it can be generalized, or even has to be?).
