### ISSUE TITLE
Integrate OpenScanHub with Packit

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2107]
As a package developer, I would like to see the result of the OpenScanHub analysis for my package so I am able to fix the possible issues when a new change is introduced.

* [x] Implement OpenScanHub integration in Packit core.
* [x] Implement a new handler to trigger the new OpenScanHub job after the Copr build is done.
* [x] Support differential check by sending the build from the base branch.

In the meantime, as a workaround, people can use `csmock` in testing farm as being tried in https://github.com/packit/hello-world/pull/1530 (similar to [example `rpminspec`setup](https://packit.dev/docs/configuration/upstream/tests/#rpminspect))

**Comment by lachmanfrantisek** [comment]
We have discussed all the epics during our Q3 planning and with our limited capacity, we -- as a Packit team -- decided to focus on other epics (see [the board](https://github.com/orgs/packit/projects/7/views/29)). For now, people can use csmock directly (as documented at https://packit.dev/docs/configuration/upstream/tests/#csmock ).

In the meantime:
* We would like to design this and agree on the workflow, messaging,...
* We are more than happy to help someone (e..g Situ..;) help us with that. (The core part should be easy to contribute.)

**Comment by lachmanfrantisek** [comment]
We didn't pick this as a top Packit team priority for the next quarter, but anyone can still help us make this happen. We are open to any collaboration and have successfully implemented/started multiple affords thanks to people outside of the Packit team.

Here, we still have a workaround and we can even improve this workaround by adding the plan to the github.com/packit/tmt-plans (~ a shared library of various tmt plans) that is currently being created...

**Comment by lachmanfrantisek** [comment]
Small update:

* Situ made the implementation in core/CLI in https://github.com/packit/packit/pull/2301
* The next step is to do the service part as described above. (Run the check by default as a follow-up to all successful Corp builds where we have base build available.)
  * We've created packit/research#213 to agree on the implementation details.

**Comment by lbarcziova** [comment]
Current TODO:
- [ ] #2454 
- [ ] packit/packit.dev#899

**Comment by lachmanfrantisek** [comment]
Logical next step is to https://github.com/packit/packit-service/issues/2516

**Comment by lachmanfrantisek** [comment]
Enhancements:
* [ ] https://github.com/packit/packit/issues/2391
  * partially solved by https://github.com/packit/packit/pull/2402
* [ ] https://github.com/packit/packit-service/issues/2515
