### ISSUE TITLE
Support list of versions for sync-release

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#2408]
### Summary

Pass around versions in a list (for New Hotness we can have just one version in the list, for Anitya version update fail)

### TODO

- [ ] Decide whether it's better fit to handle multiple versions in the handlers on service-side only, or implement it directly in the Packit API as suggested in the following points
- [ ] Adjust `sync-release` “API” call to be able to take list of versions instead of just one
    https://github.com/packit/packit/blob/d3cd78c0f90402f8b87d96ebd967cbf3d448148b/packit/api.py#L823
  - [ ] For now it makes sense to expect (can be checked with a simple `assert`) that only one version has been given, and take the first one
  - [ ] Follow ups to handle multiple versions will be opened later
- [ ] Adjust the CLI calls to the API to pass the list
- [ ] Adjust the packit-service calls to the API to pass the list

### Notes

Affects mainly `pull-from-upstream`

---

Part of #2068
