### ISSUE TITLE
Prepare and refactor events/parsers for CentOS Stream dist-git comments

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#2471]
### TODO

- [ ] Decide whether it makes sense to have duplicitous “events” for GitLab (downstream and upstream), or handle them in a similar way as @majamassarini did with the mixins (common GitLab part, common downstream/upstream part), although I'm not sure how feasible it is to use mixins here :thinking: 
- [ ] Refactor parsing of GitLab events (since there will be _upstream_ events directly via GitLab webhook and _downstream_ events provided via Fedora Messaging)
- [ ] Parse the dist-git GitLab events ([example](https://apps.fedoraproject.org/datagrepper/v2/id?id=8cae2ffc-5bab-4a6b-81f7-2ac9f93e66c4&is_raw=true&size=extra-large) of such event)
- [ ] Revamp the hierarchy for dist-git events, if necessary (afterwards the events will be coming from both GitLab and Pagure)

### ACs

- [ ] There is a **one** parser for each GitLab event, e.g., parsing of a push to either upstream on GitLab or downstream on GitLab should be parsed by one function only, there should be no duplication present that would differentiate upstream from downstream on the parsing level.
- [ ] Downstream events should have common ancestors that allow handlers to be handling **just** one ancestor for downstream.
   i.e. there should be a notion of a dist-git event in general (such as `AbstractDownstreamEvent`) and more specific ones (such as `AbstractDownstreamPushEvent`)
- [ ] Current downstream workflows **must not** be broken.
- [ ] Current upstream workflows on GitLab **must not** be broken.

### Links

Part of #2191
