### ISSUE TITLE
Improvments and fixes to our SLO rules 

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2519]
1. [ ] Fix slowness in giving feedback: ideally there should be always 0 events/minute [here](http://metrics.osci.redhat.com/d/f269a786-c129-4bc6-8afe-0475b622c4ac/slo1-graphs?orgId=1&from=1725526663832&to=1725613063832&viewPanel=42) this could be related with [issue](https://github.com/packit/packit-service/issues/2512)
2. [ ] After point 1. is solved we can also fix SLO1 rule, if in the [above graph](http://metrics.osci.redhat.com/d/f269a786-c129-4bc6-8afe-0475b622c4ac/slo1-graphs?orgId=1&from=1725526663832&to=1725613063832&viewPanel=42) there are more than 1 event/min of **no_status_after_25_s** than an alert should be fired (now it isn't - unless we have a burst of events - the considered time range is too broad and we have too few events)
3. [ ] Fix **copr_builds_queued_total** metric, it totally out of range it is **10000** time greater than *copr_builds_started_total* and *copr_builds_finished_total* which seems to be ok. A card exist for this [issue](https://github.com/packit/packit-service/issues/2430)
4. [ ] After point 3. is solved, add new Prometheus alerts for Testing Farm and Copr jobs stuck on the external service level, you can use the definition of the following graphs:
    * http://metrics.osci.redhat.com/d/accb090e-75bb-4961-8f37-aeec189bb0b7/testing-farm-and-copr-jobs-metrics?orgId=1&from=1725602638681&to=1725613438681&viewPanel=3
    * http://metrics.osci.redhat.com/d/accb090e-75bb-4961-8f37-aeec189bb0b7/testing-farm-and-copr-jobs-metrics?orgId=1&from=1725602649463&to=1725613449463&viewPanel=9
    * http://metrics.osci.redhat.com/d/accb090e-75bb-4961-8f37-aeec189bb0b7/testing-farm-and-copr-jobs-metrics?orgId=1&from=1725602666235&to=1725613466235&viewPanel=7
    * http://metrics.osci.redhat.com/d/accb090e-75bb-4961-8f37-aeec189bb0b7/testing-farm-and-copr-jobs-metrics?orgId=1&from=1725602678606&to=1725613478606&viewPanel=11
