### ISSUE TITLE
build trigger 2.0

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#47]
I propose to create a new handler, "build":
* [ ] trigger is: dist-git push, upstream PR (NOT upstream release), upstream push
* [ ] it defaults to "copr" but can be overridden to "koji"
* [x] copr chroots and koji targets can be specified

Counter-proposal to #46

This is coming from https://github.com/packit-service/packit/issues/264

**Comment by LorbusChris** [comment]
Absolutely love this!

> NOT upstream release

Shouldn't an upstream release be able to trigger a new build as well? (e.g. for projects that don't want/need a new koji build on each push, but for each new tagged release)

**Comment by TomasTomecek** [comment]
> Shouldn't an upstream release be able to trigger a new build as well? (e.g. for projects that don't want/need a new koji build on each push, but for each new tagged release)

Yes, absolutely makes sense, my point here is that I didn't want to make this too big.

**Comment by LorbusChris** [comment]
friendly ping :) is there any work on this planned in the near future? This'd be very helpful in FCOS and OKD.

**Comment by LorbusChris** [comment]
> local SRPMs can be sent to koji as well
    this is a big security concern
    if srpm==True, target can't be r"f\d\d" or rawhide

I don't understand this part. Why do we need to send locally built to koji?

**Comment by LorbusChris** [comment]
I would limit Koji builds to the master branch (or a number of explicitly declared branches on the main repo), and run PRs on COPR.

**Comment by TomasTomecek** [comment]
> > local SRPMs can be sent to koji as well
> > this is a big security concern
> > if srpm==True, target can't be r"f\d\d" or rawhide
> 
> I don't understand this part. Why do we need to send locally built srpms to koji?

Depends on what you want to achieve. If you want to bypass dist-git: create SRPMs from upstream and send them directly to koji, that's a security concern. If everything goes through dist-git, we should be fine since things can be easily audited. Actually I'm going to remove that part from the OP.

**Comment by lachmanfrantisek** [comment]
This is partially done (upstream triggers) and the downstream trigger is covered by  #55.
