### ISSUE TITLE
support building in koji for new dist-git commits

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#55]
Support koji builds for new dist-git commits.

- [ ] Verify, that we accept new events for dist-git commits.
- [ ] Implement the handler (decide with the team):
    - [ ] Either enhance the KojiBuildHandler to differentiate between upstream and downstream git forge and act differently.
    - [ ] Or, create a new handler and new job type.

Edit: complete rewrite v2 by @lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
@TomasTomecek can you elaborate on this one? The team is confused. (Is this still needed/wanted?)

**Comment by TomasTomecek** [comment]
@lachmanfrantisek good point, I actually didn't remember what this really was; updated and scoped it down as much as possible

**Comment by TomasTomecek** [comment]
Yep, we still need to be able to build downstream.

**Comment by lachmanfrantisek** [comment]
Still relevant.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek this is pretty much your task in this sprint, right?

**Comment by lachmanfrantisek** [comment]
@TomasTomecek I saw `koji` build and agreed, but this is about `propose-downstream`, isn't it? I implemented only upstream triggers -- PR, branch-push and release.

- When is this expected to run? When the downstream PR is created?
- Do we want to inform the user in upstream or downstream?

**Comment by TomasTomecek** [comment]
Good points, we'd need to spend some time on designing this. Ideally we'd just build on dist-git pushes and inform people in the upstream if something goes wrong

**Comment by lachmanfrantisek** [comment]
Laura is fixing the `sync-from-downstream` job that requires reacting to dist-git commits as well. We are getting closer.

**Comment by TomasTomecek** [comment]
Yes, we just need to figure out a mechanism for people to configure downstream jobs in the upstream - having .packit.yaml in dist-git was a dead-end from my PoV.

**Comment by lachmanfrantisek** [comment]
Thinking about this, the workflow used in upstream sends the SRPM directly to Koji so it's not what we want here.

We should:
- [ ] Verify, that we accept new events for dist-git commits.
- [ ] Implement the handler:
    - Either enhance the `KojiBuildHandler` to differentiate between upstream and downstream git forge and act differently.
    - Or, create a new handler and new job type. (A bit confusing for users but cleaner from the code perspective I think.)

**Comment by praiskup** [comment]
I interpreted this RFE incorrectly before :-( ... so lemme dump a wish here (as I believe it would be for free, if this  RFE #55 was implemented)... 

Even when Packit upstream workflow is not in use -- it would be nice if we (maintainers) could just manually push to dist-git, and the build was automatically submitted into Koji (submit can be done by any service, but if Packit did this, I'm +1).  Configuration like this would be enough.
```
auto-koji-build-upon-push: [praiskup, ...]
```
It would be a pity if we bound this cool thing only to upstream-packit workflows, and to the `propose_downstream`.
I feel a slight mismatch here... meh, so in case this is inapropriate request - perhaps we should consider if we shouldn't implement something like this elsewhere...

**Comment by praiskup** [comment]
> auto-koji-build-upon-push: [praiskup, ...]

I mean, I don't want to break releng's scripts, etc. - so perhaps we shouldn't trigger builds for everybody without asking ... therefore the configured list of push event "authors"...

**Comment by lachmanfrantisek** [comment]
@praiskup You are right, the term `propose-downstream` is here a bit misleading. The task (as I understand it) is to react to a new dist-git commit and submit a koji build for that commit.

The (only) question here is, how this can be configured/enabled (can be combined):
* Packit config in downstream.
* Hardcoded in the service.
* Dashboard or some web-UI to enable this.
* Some comment/issue we can react on and automatically save this value to the database.
* ... anything else?

**Comment by praiskup** [comment]
Anything works for me (if that matters) but if *the* config lived in dist-git, that would be super trivial to setup IMO.

**Comment by csomh** [comment]
I'm wondering if it would make sense for this and #74 to be two bots, separate from packit-service. I have the feeling we could reach a wider audience this way. For one, we wouldn't need to explain the relationship with packit-service. From a design POV: these bots would operate purely in the Fedora echo-system, and wouldn't need access to anything GitHub.

Or at least: decouple the configuration for auto-building and auto-update-creation from packit configs. Again: the reason for this being to reach a wider audience.

**Comment by lachmanfrantisek** [comment]
We should have a card to discuss our plans for downstream so just a few notes for the assigned person to cover more points of view on this:
* Configuration / how to enable this (packit config x separate service to turn this on x ...)
* Code (inside packit and reuse all the listeners and scheduling x do a separate service from scratch)
* Packit's instance (reuse the one(s) we have x separate)
* Fedora identity in downstream (do we need/want to ask for a new one?)

Regarding the wider audience, do you think creating a new service can bring a wider audience? (We already promised our plans for this on behalf of Packit that finally is somehow known.)

After some thinking about this, I like the idea of decoupling the configuration and adding the functionality as new handlers. Or start with packit config, implement the functionality, test it with packit configs in downstream and do the separate (proper) way of turning this on afterwards. (To have smaller chunks of work and some MVP sooner.)

**Comment by lachmanfrantisek** [comment]
sync to jira

**Comment by lachmanfrantisek** [comment]
sync to jira, please

**Comment by lachmanfrantisek** [comment]
sync to jira, pretty please
