### ISSUE TITLE
Create issue for failed actions triggered by branch/release trigger

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#847]
- There is an interface for showing status/logs for branch/release builds, but there is no space for more details (what we put to the comments in PRs), no notification and no way to retrigger.
- Long-term solution of this #780

AC:
- [ ] create an issue in case of an error
  - Issue has a consistent name (e.g. `[packit] build for branch master failed`) and can be reused/reopened.
- [ ] putting a `/packit build` comment will retrigger the build (same for tests)
- [ ] allow user to create this issue as well (ideally, retrigger also without need to create a comment) (nice-to-have = can be done later)

**Comment by lachmanfrantisek** [comment]
Counter proposal:

- Use commit comments instead. The problematic part is the matching from commit to trigger. (One commit can be HEAD of multiple branches and also a release.)

**Comment by lachmanfrantisek** [comment]
This will take some time but we still want to do it.

**Comment by lachmanfrantisek** [comment]
Yes, we want this. Would be nice to implement re-triggering together with this.

**Comment by lachmanfrantisek** [comment]
This would be tough work but would improve the code and will allow a lot of UX improvements. So, reopening, but not sure when we have some time for that.
